# Generated by Django 5.1.4 on 2025-01-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0004_remove_product_images_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='brand_images/%Y/%m/%d'),
        ),
    ]
